[package]
name = "hellberry-bead"
version = "0.1.0"
edition = "2024"

[features]
default = ["arduino-uno"]
arduino-uno = ["arduino-hal/arduino-uno"]

[[bin]]
name = "hellberry-bead"
test = false
bench = false

[dependencies]
nb = "1.1.0"
embedded-hal = "1.0"
paste = "1.0.15"

[dependencies.arduino-hal]
git = "https://github.com/rahix/avr-hal"
rev = "fafaf587a32a4500239fd073f89d1b9c36b48092"

[dependencies.avr-device]
version = "0.7.0"

[profile.dev]
panic = "abort"
lto = true
opt-level = "s"

[profile.release]
panic = "abort"
codegen-units = 1
debug = true
lto = true
opt-level = "s"
